# Generated by Django 2.1.2 on 2018-11-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteis', '0002_hotel_valor_diaria'),
        ('voos', '0002_voo_valor'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteis.Hotel')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.Voo')),
            ],
        ),
    ]
