# Generated by Django 2.1.2 on 2018-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='diarias',
            field=models.IntegerField(null=True),
        ),
    ]
