# Generated by Django 2.1.2 on 2018-11-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0002_voo_valor'),
        ('vendas', '0002_venda_diarias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='voo',
        ),
        migrations.AddField(
            model_name='venda',
            name='voo_ida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ida', to='voos.Voo'),
        ),
        migrations.AddField(
            model_name='venda',
            name='voo_volta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volta', to='voos.Voo'),
        ),
    ]
