# Generated by Django 2.1.2 on 2018-11-02 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_vendacomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='realizada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
