# Generated by Django 2.1.2 on 2018-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_realizada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_viagem',
            field=models.DateField(null=True),
        ),
    ]
