# Generated by Django 2.1.2 on 2018-10-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('partida', models.DateTimeField()),
                ('chegada', models.DateTimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='voos.Aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='voos.Aeroporto')),
            ],
        ),
    ]
