# Generated by Django 2.1.2 on 2018-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
